// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbcpol5WMKniyklxaK3o0jFYtfuzYOMpA',
    appId: '1:119104236762:web:ee9b9dd728cf2d0a7709e3',
    messagingSenderId: '119104236762',
    projectId: 'credbud-14b00',
    authDomain: 'credbud-14b00.firebaseapp.com',
    storageBucket: 'credbud-14b00.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1vV2kIUCa54-Y9Cl2_NF5Oue7BqrF-DQ',
    appId: '1:119104236762:android:a8db148998d3dcab7709e3',
    messagingSenderId: '119104236762',
    projectId: 'credbud-14b00',
    storageBucket: 'credbud-14b00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA26jgNAV03aplXiGvfRrCBXsyhkB5o8M',
    appId: '1:119104236762:ios:7f8f8c6354858ae97709e3',
    messagingSenderId: '119104236762',
    projectId: 'credbud-14b00',
    storageBucket: 'credbud-14b00.appspot.com',
    iosBundleId: 'tech.v1ack.credbud',
  );
}
